### ISSUE TITLE
Screen cap failed 

### ISSUE THREAD

**Issue by TheRicers** [ACK72/PlayBridge#7]
![image](https://github.com/user-attachments/assets/6ae696dd-6d53-4282-bab2-111badc15b31)
im encountering this problem while using playbridge, it connects but then shows be screencap failed, i tried the screenshot test and it shows me this: 
`MAA has encountered an error
	Cannot read from the stream.
Failed to read from the stream. (0x88982F72)
Solution
	Unknown error occurred
Details
System.IO.IOException: Cannot read from the stream.
 ---> System.Runtime.InteropServices.COMException (0x88982F72): Failed to read from the stream. (0x88982F72)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at MaaWpfGui.Main.AsstProxy.AsstGetImage(IntPtr handle)
   at MaaWpfGui.Main.AsstProxy.<>c__DisplayClass16_0.<AsstGetImageAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.Main.AsstProxy.AsstGetImageAsync(IntPtr handle)
   at MaaWpfGui.Main.AsstProxy.AsstGetFreshImageAsync()
   at MaaWpfGui.ViewModels.UserControl.Settings.ConnectSettingsUserControlModel.TestLinkAndGetImage()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`
   
here are the logs
[asst.log](https://github.com/user-attachments/files/17967730/asst.log)
[gui.log](https://github.com/user-attachments/files/17967731/gui.log)
[playbridge.log](https://github.com/user-attachments/files/17967733/playbridge.log)

i hope i can find a solution, thanks

**Comment by ACK72** [comment]
It's hard to tell where the error is coming from based on the information you've provided.
If you're still experiencing the error, please reopen the issue.

The PLAYBRIDGE_TITLE variable in the cmd script could/might be incorrect, I think..
